spring:
  rabbitmq:
    host: ${PM_AGENT_RABBITMQ_HOST:10.144.48.123}
    port: ${PM_AGENT_RABBITMQ_PORT:5672}
    username: ${PM_AGENT_RABBITMQ_USERNAME:pm-agent}
    password: ${PM_AGENT_RABBITMQ_PASSWORD:pm-agent-dev}
    virtual-host: ${PM_AGENT_RABBITMQ_VHOST:pm-agent}
    connection-timeout: 3s
    requested-heartbeat: 30s
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: false
