### 健康检查
# @name health
GET {{baseUrl}}/internal/health
X-Trace-Id: http-health-{{$uuid}}

### 注册测试用户
# 首次使用执行；如果邮箱已存在，直接执行后面的登录请求。
# @name register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json
X-Trace-Id: http-auth-register-{{$uuid}}

{
  "username": "{{RegisterUsername}}",
  "email": "{{RegisterEmail}}",
  "password": "{{RegisterPassword}}"
}

### 用户登录
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
X-Trace-Id: http-auth-login-{{$uuid}}

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

### 错误密码登录
# @name loginWithWrongPassword
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
X-Trace-Id: http-auth-login-failed-{{$uuid}}

{
  "email": "{{Email}}",
  "password": "12868751784"
}


### 黑名单用户登录
# @name loginWithDisableUser
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
X-Trace-Id: http-auth-login-failed-{{$uuid}}

{
  "email": "{{DisabledEmail}}",
  "password": "123456"
}

### 注销当前登录状态——最后执行
# @name logout
POST {{baseUrl}}/api/v1/auth/logout
Authorization: Bearer {{accessToken}}
X-Trace-Id: http-auth-logout-{{$uuid}}
