CREATE TABLE pm_event_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    event_id VARCHAR(64) NOT NULL COMMENT '事件幂等 ID',
    event_type VARCHAR(128) NOT NULL COMMENT '事件类型',
    exchange_name VARCHAR(128) NOT NULL COMMENT 'RabbitMQ 交换机',
    routing_key VARCHAR(128) NOT NULL COMMENT 'RabbitMQ routing key',
    payload_json JSON NOT NULL COMMENT '事件 JSON 载荷',
    status VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT '发布状态',
    publish_attempts INT NOT NULL DEFAULT 0 COMMENT '发布尝试次数',
    next_retry_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次重试时间',
    published_at DATETIME NULL COMMENT '确认发布时间',
    last_error VARCHAR(500) NULL COMMENT '最后一次发布错误摘要',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_outbox_event_id (event_id),
    KEY idx_event_outbox_pending (status, next_retry_at, id),
    CONSTRAINT ck_event_outbox_status CHECK (status IN ('pending', 'published')),
    CONSTRAINT ck_event_outbox_attempts CHECK (publish_attempts >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='RabbitMQ 事务消息 Outbox';
