bind 0.0.0.0
protected-mode yes
port 6379

daemonize no
supervised no

dir /data

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

databases 16

timeout 0
tcp-keepalive 60

loglevel notice
