"""正式上下文任务风险与检索闭环

Revision ID: 20260912_01
Revises: 20260910_02
Create Date: 2026-09-12 12:31:55.400325
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '20260912_01'
down_revision: str | None = '20260910_02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_confirmation_receipt',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('receipt_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('base_revision', sa.Integer(), nullable=False),
    sa.Column('committed_revision', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('superseded_draft_ids', sa.JSON(), nullable=False),
    sa.Column('projection', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uk_action_receipt_project_idem'),
    sa.UniqueConstraint('project_id', 'receipt_id', name='uk_action_receipt_project')
    )
    op.create_table('agent_action_draft',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('origin_revision', sa.Integer(), nullable=False),
    sa.Column('expected_entity_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('result_ref', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending','confirmed','superseded','rejected','expired','executing','succeeded','partial','failed','conflicted')", name='ck_action_draft_state'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uk_action_draft_project_idem')
    )
    op.create_index('ix_action_draft_project_state', 'agent_action_draft', ['project_id', 'origin_revision', 'state'], unique=False)
    op.create_table('agent_context_asset',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_ref', sa.String(length=512), nullable=True),
    sa.Column('snapshot_version', sa.String(length=128), nullable=True),
    sa.Column('snapshot_state', sa.String(length=16), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('project_constraint','long_term_memory','short_term_memory','user_preference')", name='ck_context_asset_type'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'subject_user_id', 'asset_type', name='uk_context_asset_scope_type')
    )
    op.create_table('agent_context_asset_change',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_item_id', sa.BigInteger(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('before_digest', sa.String(length=64), nullable=True),
    sa.Column('after_digest', sa.String(length=64), nullable=True),
    sa.Column('source_event_id', sa.String(length=128), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_context_change_target', 'agent_context_asset_change', ['project_id', 'target_type', 'target_item_id'], unique=False)
    op.create_table('context_update_batch',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=False),
    sa.Column('source_event_type', sa.String(length=48), nullable=False),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=64), nullable=False),
    sa.Column('producer_version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('base_target_versions', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('causation_id', sa.String(length=128), nullable=True),
    sa.Column('hop_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('envelope', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uk_context_batch_project_idem')
    )
    op.create_index('ix_context_batch_project_revision', 'context_update_batch', ['project_id', 'project_revision'], unique=False)
    op.create_foreign_key(
        'fk_context_change_batch',
        'agent_context_asset_change',
        'context_update_batch',
        ['batch_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_table('pm_risk',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_type', sa.String(length=64), nullable=False),
    sa.Column('root_cause', sa.String(length=500), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('affected_refs', sa.JSON(), nullable=False),
    sa.Column('mitigation_summary', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_action_draft_id', sa.BigInteger(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('confirmed','mitigating','resolved','closed')", name='ck_risk_status'),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='ck_risk_impact'),
    sa.CheckConstraint('probability BETWEEN 1 AND 5', name='ck_risk_probability'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_action_draft_id', name='uk_risk_action_draft')
    )
    op.create_index('ix_risk_project_fingerprint', 'pm_risk', ['project_id', 'fingerprint', 'status'], unique=False)
    op.create_index('ix_risk_project_status_level', 'pm_risk', ['project_id', 'status', 'level'], unique=False)
    op.create_index('ix_risk_project_type_status', 'pm_risk', ['project_id', 'risk_type', 'status'], unique=False)
    op.create_table('pm_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('milestone_ref', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assignee_user_id', sa.BigInteger(), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('resume_status', sa.String(length=24), nullable=True),
    sa.Column('source_action_draft_id', sa.BigInteger(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','developing','integrating','testing','blocked','done','cancelled')", name='ck_task_status'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_action_draft_id', name='uk_task_action_draft')
    )
    op.create_index('ix_task_project_assignee', 'pm_task', ['project_id', 'assignee_user_id', 'status'], unique=False)
    op.create_index('ix_task_project_due', 'pm_task', ['project_id', 'due_at', 'status'], unique=False)
    op.create_index('ix_task_project_status', 'pm_task', ['project_id', 'status', 'deleted_at'], unique=False)
    op.create_table('project_analysis_run',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('target_project_revision', sa.Integer(), nullable=False),
    sa.Column('analysis_generation', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('degraded_components', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending','processing','succeeded','succeeded_with_warnings','failed','superseded')", name='ck_analysis_run_state'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uk_analysis_project_idem')
    )
    op.create_index('ix_analysis_project_revision', 'project_analysis_run', ['project_id', 'target_project_revision'], unique=False)
    op.create_table('retrieval_corpus_state',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('published_revision', sa.Integer(), nullable=False),
    sa.Column('lexical_state', sa.String(length=16), nullable=False),
    sa.Column('vector_state', sa.String(length=16), nullable=False),
    sa.Column('vector_generation', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uk_retrieval_corpus_project')
    )
    op.create_table('retrieval_document',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('authority_kind', sa.String(length=32), nullable=False),
    sa.Column('authority_version', sa.String(length=128), nullable=False),
    sa.Column('semantic_version', sa.String(length=128), nullable=False),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chunker_version', sa.String(length=32), nullable=False),
    sa.Column('lexicon_version', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_version', sa.String(length=128), nullable=True),
    sa.Column('vector_state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','deleted')", name='ck_retrieval_document_status'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_type', 'source_id', name='uk_retrieval_document_source')
    )
    op.create_index('ix_retrieval_document_revision', 'retrieval_document', ['project_id', 'project_revision', 'status'], unique=False)
    op.create_table('retrieval_evidence_edge',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('from_ref', sa.String(length=191), nullable=False),
    sa.Column('to_ref', sa.String(length=191), nullable=False),
    sa.Column('relation', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','deleted')", name='ck_retrieval_edge_status'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'from_ref', 'to_ref', 'relation', name='uk_retrieval_edge')
    )
    op.create_index('ix_retrieval_edge_from', 'retrieval_evidence_edge', ['project_id', 'from_ref'], unique=False)
    op.create_table('retrieval_index_job',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('operation', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('authority_version', sa.String(length=128), nullable=False),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending','succeeded','failed','superseded')", name='ck_retrieval_job_state'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uk_retrieval_job_idem')
    )
    op.create_index('ix_retrieval_job_state', 'retrieval_index_job', ['state', 'next_retry_at'], unique=False)
    op.create_table('agent_context_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('semantic_key', sa.String(length=191), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('review_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['agent_context_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'semantic_key', name='uk_context_asset_semantic')
    )
    op.create_index('ix_context_item_asset_state', 'agent_context_item', ['asset_id', 'status', 'expires_at'], unique=False)
    op.create_table('context_update_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_item_id', sa.BigInteger(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expected_target_version', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('persisted_ref', sa.String(length=128), nullable=True),
    sa.Column('result_version', sa.Integer(), nullable=True),
    sa.Column('index_sync_status', sa.String(length=24), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedup_fingerprint', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['context_update_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'candidate_id', name='uk_context_item_candidate')
    )
    op.create_index('ix_context_update_state', 'context_update_item', ['project_id', 'state', 'next_retry_at'], unique=False)
    op.create_table('pm_risk_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('risk_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=False),
    sa.Column('after_state', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_action_draft_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['pm_risk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_event_risk', 'pm_risk_event', ['risk_id', 'id'], unique=False)
    op.create_table('pm_risk_evidence',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('risk_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=False),
    sa.Column('anchor', sa.JSON(), nullable=False),
    sa.Column('support_relation', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['pm_risk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'evidence_type', 'source_id', 'source_version', name='uk_risk_evidence_source')
    )
    op.create_table('pm_risk_task',
    sa.Column('risk_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['pm_risk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['pm_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', 'task_id', 'relation_type'),
    sa.UniqueConstraint('risk_id', 'task_id', 'relation_type', name='uk_risk_task')
    )
    op.create_table('pm_task_dependency',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('depends_on_task_id', sa.BigInteger(), nullable=False),
    sa.Column('dependency_type', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name='ck_task_dependency_self'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['pm_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['pm_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uk_task_dependency')
    )
    op.create_table('pm_task_status_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_action_draft_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['pm_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_status_log_task', 'pm_task_status_log', ['task_id', 'id'], unique=False)
    op.create_table('retrieval_chunk',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_key', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('chunk_kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_terms', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('anchor', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redaction_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','deleted')", name='ck_retrieval_chunk_status'),
    sa.ForeignKeyConstraint(['document_id'], ['retrieval_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_key', name='uk_retrieval_chunk_key')
    )
    op.create_index('ix_retrieval_chunk_document_status', 'retrieval_chunk', ['document_id', 'status', 'ordinal'], unique=False)
    op.create_table('agent_trusted_chat_evidence',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('message_sha256', sa.String(length=64), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['context_update_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['agent_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'batch_id', name='uk_chat_evidence_batch'),
    sa.UniqueConstraint('project_id', 'event_id', name='uk_chat_evidence_event')
    )
    op.add_column(
        'pm_project',
        sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    op.add_column(
        'pm_project',
        sa.Column(
            'published_revision',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    op.add_column(
        'pm_project_file',
        sa.Column(
            'content_origin_revision',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    op.add_column(
        'pm_project_file',
        sa.Column(
            'last_observed_revision',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    op.add_column(
        'pm_project_file',
        sa.Column(
            'may_supply_constraints',
            sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE pm_project_file SET may_supply_constraints=1 "
        "WHERE LOWER(REPLACE(COALESCE(extension,''),'.','')) "
        "IN ('md','mdx','rst','txt','docx','pdf') AND ("
        "LOWER(REPLACE(relative_path,'\\\\','/')) LIKE 'docs/%' OR "
        "LOWER(REPLACE(relative_path,'\\\\','/')) LIKE 'doc/%' OR "
        "LOWER(relative_path) LIKE 'readme%' OR "
        "LOWER(relative_path) LIKE '%spec%' OR "
        "LOWER(relative_path) LIKE '%requirement%' OR "
        "relative_path LIKE '%规范%' OR relative_path LIKE '%设计%' OR "
        "relative_path LIKE '%需求%')"
    )
    op.create_check_constraint(
        'ck_project_revision_order',
        'pm_project',
        'revision >= published_revision AND published_revision >= 0',
    )
    op.create_check_constraint(
        'ck_project_file_revision_nonnegative',
        'pm_project_file',
        'content_origin_revision >= 0 AND last_observed_revision >= 0',
    )
    op.alter_column('pm_project', 'revision', server_default=None)
    op.alter_column('pm_project', 'published_revision', server_default=None)
    op.alter_column('pm_project_file', 'content_origin_revision', server_default=None)
    op.alter_column('pm_project_file', 'last_observed_revision', server_default=None)
    op.alter_column('pm_project_file', 'may_supply_constraints', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_project_file_revision_nonnegative',
        'pm_project_file',
        type_='check',
    )
    op.drop_constraint('ck_project_revision_order', 'pm_project', type_='check')
    op.drop_column('pm_project_file', 'may_supply_constraints')
    op.drop_column('pm_project_file', 'last_observed_revision')
    op.drop_column('pm_project_file', 'content_origin_revision')
    op.drop_column('pm_project', 'published_revision')
    op.drop_column('pm_project', 'revision')
    op.drop_table('agent_trusted_chat_evidence')
    op.drop_table('retrieval_chunk')
    op.drop_table('pm_task_status_log')
    op.drop_table('pm_task_dependency')
    op.drop_table('pm_risk_task')
    op.drop_table('pm_risk_evidence')
    op.drop_table('pm_risk_event')
    op.drop_table('context_update_item')
    op.drop_table('agent_context_item')
    op.drop_table('retrieval_index_job')
    op.drop_table('retrieval_evidence_edge')
    op.drop_table('retrieval_document')
    op.drop_table('retrieval_corpus_state')
    op.drop_table('project_analysis_run')
    op.drop_table('pm_task')
    op.drop_table('pm_risk')
    op.drop_table('agent_context_asset_change')
    op.drop_table('context_update_batch')
    op.drop_table('agent_context_asset')
    op.drop_table('agent_action_draft')
    op.drop_table('agent_action_confirmation_receipt')
    # ### end Alembic commands ###
